### ISSUE TITLE
settings.txt syntax error

### ISSUE THREAD

**Issue by mattk926** [IfThenERROR/autoedit#1]
Line 20 has a syntax error with an extra ( in the `.tr("|",("_")}`

`nameFormatSeries='/home/osmc/TV/{n.ascii().replaceAll(/[?]+$/).tr("–","_").tr("*","_").tr("|",("_")} ({y})/{s00e00}.{t.ascii().replaceAll(/[?]+$/).tr(":","_").tr("*","_").tr("|","_")}'`

**Comment by IfThenERROR** [comment]
Thanks, corrected!
