### ISSUE TITLE
not 16:9 if encoded with h264_omx

### ISSUE THREAD

**Issue by the-unknown** [IfThenERROR/autoedit#2]
Hey,

so today I tried your script on my little RasPi.
The input-file is 16:9 mpeg2 TS file: `Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc`
After your script did the encoding with h264_omx, the result file is not in 16:9 format, but in 4:3 format although the size did not change at all: `Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 720x576, 25 tbr, 90k tbn, 180k tbc`

What do I have to change, that the final result is still 16:9 and not progressive (gives ugly scan-lines)?

**Comment by IfThenERROR** [comment]
Problem cannot be reproduced. Seems to be an issue with the source file or container format, not with the script.
